name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: fmt
      run: cargo fmt --all --check
    - name: build
      run: cargo build --verbose --all-targets --all-features --all
    - name: clippy
      run: cargo clippy --verbose --all --all-features
    - name: test
      run: cargo test --verbose --all
